name: Tests

on:
  pull_request:

  push:
    branches:
      - main
      - 'feature/**'
      - 'support/**'

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false

      matrix:
        linters:
          - description: Lint Sass
            run: npm run lint:scss

          - description: Lint JavaScript
            run: npm run lint:js

          - description: Prettier
            run: npm run lint:prettier

          - name: Run task

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: npm
          check-latest: true
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build

      - name: Run linter
        id: lint
        run: ${{ matrix.linter.run }}

      - name: Check links
        run: npm run check-links
